name: CI

on:
  push:
    branches: [ "master", "github-action-test" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Run test on ${{ matrix.os }} with Xcode ${{ matrix.xcode-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            xcode-version: '16.4'
            swift-version: '6.0'
          - os: macos-14
            xcode-version: '15.4'
            swift-version: '5.10'
          - os: macos-14
            xcode-version: '15.2'
            swift-version: '5.9'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v1

    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode-version }}.app

    - name: Find available iOS Simulator
      id: simulator
      run: |
        AVAILABLE=$(xcrun simctl list devices available | grep -m1 "iPhone" | awk -F '[()]' '{print $2}')
        echo "udid=$AVAILABLE" >> $GITHUB_OUTPUT

    - name: Build
      run: |
        xcodebuild build-for-testing \
          -scheme VWO-FME \
          -sdk iphonesimulator \
          -configuration Debug

    - name: Test with Coverage
      run: |
        xcodebuild test \
          -scheme VWO-FMETests \
          -destination "id=${{ steps.simulator.outputs.udid }}" \
          -sdk iphonesimulator \
          -configuration Debug \
          -enableCodeCoverage YES \
          -resultBundlePath ./TestResults.xcresult \
          -verbose

    - name: Generate Coverage Report
      run: |
        xcrun xccov view --report --files-for-target VWO-FME ./TestResults.xcresult
